# Generated by Django 5.2.1 on 2025-06-02 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('source_type', models.CharField(choices=[('news', 'News API'), ('rss', 'RSS Feed'), ('gov', 'Government'), ('social', 'Social Media')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.URLField(unique=True)),
                ('published_at', models.DateTimeField()),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('tags', models.JSONField(default=list)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('summary', models.TextField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.source')),
            ],
        ),
    ]
