# Generated by Django 5.2.1 on 2025-06-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_article_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary_structured',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
