# Generated by Django 5.2.1 on 2025-06-04 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_article_summary_structured'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='source',
            name='last_fetched',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='notes',
            field=models.TextField(blank=True, help_text='Scraping notes, known issues, etc.'),
        ),
        migrations.AddField(
            model_name='source',
            name='parser_override',
            field=models.CharField(blank=True, help_text="Force parser method (e.g., 'rss', 'json', 'html')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='trust_score',
            field=models.FloatField(default=0.5, help_text='0 = untrusted, 1 = highly trusted'),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(choices=[('news', 'News API'), ('rss', 'RSS Feed'), ('gov', 'Government'), ('social', 'Social Media'), ('custom', 'Custom Scraper')], max_length=50),
        ),
        migrations.CreateModel(
            name='SourceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('header', 'HTTP Header'), ('param', 'URL Parameter'), ('rate_limit', 'Rate Limit'), ('parser', 'Parser Override'), ('postprocess', 'Post-processing'), ('auth', 'Auth Token'), ('user_agent', 'User-Agent'), ('transform', 'Content Transform')], max_length=50)),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='news.source')),
            ],
        ),
    ]
